# Generated by Django 4.2.3 on 2023-09-24 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CampusLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='地点名称')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='纬度')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='经度')),
                ('description', models.TextField(blank=True, null=True, verbose_name='简介')),
                ('radius', models.PositiveIntegerField(blank=True, verbose_name='范围（米）')),
                ('image', models.ImageField(upload_to='images/CampusLocation/', verbose_name='地点照片')),
            ],
            options={
                'verbose_name': '校园标志地点',
                'verbose_name_plural': '校园标志地点',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, verbose_name='礼品名称')),
                ('description', models.TextField(verbose_name='礼品描述')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='价格')),
                ('stock', models.PositiveIntegerField(verbose_name='库存数量')),
                ('image', models.ImageField(blank=True, null=True, upload_to='wx_api/static/img/products/', verbose_name='礼品图片')),
            ],
            options={
                'verbose_name': '积分礼品仓库',
                'verbose_name_plural': '积分礼品仓库',
            },
        ),
        migrations.CreateModel(
            name='SchoolCulturl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('image', models.ImageField(upload_to='images/SchoolCulturl/')),
            ],
            options={
                'verbose_name': '校园文化数据',
                'verbose_name_plural': '校园文化数据',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('nickname', models.CharField(max_length=63, verbose_name='昵称')),
                ('wx_openid', models.CharField(max_length=63, primary_key=True, serialize=False, unique=True, verbose_name='微信登录openid')),
                ('registration_time', models.DateTimeField(blank=True, null=True, verbose_name='用户注册时间')),
                ('last_login_time', models.DateTimeField(blank=True, null=True, verbose_name='用户最后一次登录时间')),
                ('avatar', models.ImageField(null=True, upload_to='images/UserInfo_avatar/', verbose_name='用户头像')),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
            },
        ),
        migrations.CreateModel(
            name='UserProgressRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.PositiveIntegerField(verbose_name='用户积分')),
                ('wx_openid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='wx_api.userinfo', verbose_name='微信登录openid')),
            ],
            options={
                'verbose_name': '用户积分数据',
                'verbose_name_plural': '用户积分数据',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='反馈内容')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='反馈时间')),
                ('wx_openid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wx_api.userinfo', verbose_name='微信登录openid')),
            ],
            options={
                'verbose_name': '用户反馈建议',
                'verbose_name_plural': '用户反馈建议',
            },
        ),
    ]
