# Generated by Django 4.2.3 on 2023-09-24 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wx_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRedemptionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redemption_date', models.DateTimeField(auto_now_add=True, verbose_name='兑换时间')),
                ('points_spent', models.PositiveIntegerField(verbose_name='消耗积分')),
                ('redemption_method', models.CharField(choices=[('积分', '积分'), ('游戏兑换', '游戏兑换'), ('地点打卡兑换', '地点打卡兑换')], max_length=20, verbose_name='兑换方式')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wx_api.product', verbose_name='兑换礼品')),
                ('wx_openid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wx_api.userinfo', verbose_name='微信登录openid')),
            ],
            options={
                'verbose_name': '用户积分兑换记录',
                'verbose_name_plural': '用户积分兑换记录',
            },
        ),
    ]
